# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui_files\healthcare_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(676, 527)
        self.groupBox_4 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_4.setGeometry(QtCore.QRect(40, 30, 281, 201))
        self.groupBox_4.setObjectName("groupBox_4")
        self.totalClientsLabel = QtWidgets.QLabel(self.groupBox_4)
        self.totalClientsLabel.setGeometry(QtCore.QRect(90, 30, 91, 16))
        self.totalClientsLabel.setObjectName("totalClientsLabel")
        self.totalClientsLabel_l = QtWidgets.QLabel(self.groupBox_4)
        self.totalClientsLabel_l.setGeometry(QtCore.QRect(10, 30, 81, 16))
        self.totalClientsLabel_l.setObjectName("totalClientsLabel_l")
        self.groupBox_7 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_7.setGeometry(QtCore.QRect(340, 40, 321, 181))
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_7)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(60, 50, 195, 111))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.logout = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.logout.setAutoDefault(False)
        self.logout.setObjectName("logout")
        self.verticalLayout.addWidget(self.logout)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 280, 451, 201))
        self.groupBox_2.setObjectName("groupBox_2")
        self.client_manage_list = QtWidgets.QComboBox(self.groupBox_2)
        self.client_manage_list.setGeometry(QtCore.QRect(10, 30, 431, 32))
        self.client_manage_list.setObjectName("client_manage_list")
        self.client_manage_list.addItem("")
        self.manage_client = QtWidgets.QPushButton(self.groupBox_2)
        self.manage_client.setGeometry(QtCore.QRect(170, 110, 100, 32))
        self.manage_client.setAutoDefault(False)
        self.manage_client.setObjectName("manage_client")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox_4.setTitle(_translate("Dialog", "Healthcare Summary"))
        self.totalClientsLabel.setText(_translate("Dialog", "Total Patients:"))
        self.totalClientsLabel_l.setText(_translate("Dialog", "Total Patients:"))
        self.groupBox_7.setTitle(_translate("Dialog", "Actions"))
        self.logout.setText(_translate("Dialog", "Log out"))
        self.groupBox_2.setTitle(_translate("Dialog", "Manage Patients"))
        self.client_manage_list.setItemText(0, _translate("Dialog", "Clients List"))
        self.manage_client.setText(_translate("Dialog", "Manage"))
